spring.application.name=JMSProj-01-ReceiverApp
# ActiveMQ Broker URL
spring.activemq.broker-url=tcp://localhost:61616

# Credentials (if authentication is enabled)
spring.activemq.user=admin
spring.activemq.password=admin

# Use point-to-point (Queue) messaging
spring.jms.pub-sub-domain=true